Revert "Add build for Node26"
This reverts commit a1bc5db733c7b0c0787a42c99816c08ba40e154c.

Apparently this is not supported yet by setup-node:

    Attempting to download 26...
    Error: Unable to find Node version '26' for platform linux and architecture x64.